//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Model.EF._1012
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSP_Products
    {
        public int PRODUCTID { get; set; }
        public string PRODUCTNUMBER { get; set; }
        public string DESCRIPTION { get; set; }
        public string DIAMETER { get; set; }
        public Nullable<double> LENGTH { get; set; }
        public Nullable<double> WEIGHT { get; set; }
        public Nullable<int> PRESSURE { get; set; }
        public Nullable<double> VOLUME { get; set; }
        public string MRN { get; set; }
        public string MATDESC { get; set; }
        public string ITEMTYPE { get; set; }
        public string ITEMSTATUS { get; set; }
        public string ISDELETED { get; set; }
    }
}
