//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Model.EF._1012
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSP_Matrix_DisplacerAlternateWeight
    {
        public int Alternate_Weight_ID { get; set; }
        public Nullable<int> Sensor_ID { get; set; }
        public Nullable<int> Material_ID { get; set; }
        public Nullable<int> Thickness_ID { get; set; }
        public Nullable<decimal> Alternate_Weight_Value { get; set; }
    }
}
