//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Model.EF._1012
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSP_TT_Material
    {
        public int TT_Material_ID { get; set; }
        public string TT_Material_Name { get; set; }
    }
}
