//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Model.EF._1012
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT_ActuatorModel_Base
    {
        public int ActuatorModelId { get; set; }
        public int ActuatorTypeId { get; set; }
        public string ActuatorModelName { get; set; }
        public string ManufacturerName { get; set; }
        public string TravelUOM { get; set; }
        public Nullable<decimal> TravelMin { get; set; }
        public Nullable<decimal> TravelMax { get; set; }
        public string TravelRange { get; set; }
        public string Housing { get; set; }
        public string MountingAccessory { get; set; }
        public Nullable<decimal> ListPrice { get; set; }
        public string PartNumber { get; set; }
        public string CommentText { get; set; }
        public string FSNumber { get; set; }
        public bool VisibleOnTheWeb { get; set; }
    }
}
