//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Model.EF._1012
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT_ActuatorModel_Multiple
    {
        public int ActuatorModelMultipleId { get; set; }
        public int ActuatorModelId { get; set; }
        public int ActuatorTypeId { get; set; }
        public string FSNumber { get; set; }
        public Nullable<decimal> FactoryPrice { get; set; }
        public Nullable<decimal> FieldPrice { get; set; }
        public Nullable<decimal> VIPSELLPrice { get; set; }
        public Nullable<int> EMModulesNumber { get; set; }
        public bool VisibleOnTheWeb { get; set; }
        public bool VisibleOnEMFlag { get; set; }
        public bool VisibleOnOEDIFlag { get; set; }
    }
}
