//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Model.EF._1012
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTypeTranslation
    {
        public int Organization_ID { get; set; }
        public int Transaction_Type_Id { get; set; }
        public string LBPValue { get; set; }
    }
}
