//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Model.EF._1012
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_F_TypeTemplate
    {
        public string ID { get; set; }
        public string Version { get; set; }
        public string TemplateXml { get; set; }
        public string IsPublish { get; set; }
        public string TempID { get; set; }
    
        public virtual T_F_TypeTemplateGroup T_F_TypeTemplateGroup { get; set; }
    }
}
