//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Model.EF._1012
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_F_MetaData_UIInstance
    {
        public string ID { get; set; }
        public string UIID { get; set; }
        public string MainEntityInstanceID { get; set; }
        public int Version { get; set; }
        public string AccessoriesID { get; set; }
        public bool IsDelete { get; set; }
    }
}
