//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Model.EF._1012
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_F_HistoryData
    {
        public string ID { get; set; }
        public string UIInstanceID { get; set; }
        public int Version { get; set; }
        public string EntityID { get; set; }
        public string ColID { get; set; }
        public string Value { get; set; }
        public System.DateTime ModifyTime { get; set; }
        public string UserID { get; set; }
        public string UIID { get; set; }
    }
}
