//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Model.EF._1012
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_F_MetaData_DataEntityCol
    {
        public string ColID { get; set; }
        public string Name { get; set; }
        public string EntityID { get; set; }
        public int OrderID { get; set; }
        public string FieldName { get; set; }
        public int FieldType { get; set; }
        public int BaseDataTypeID { get; set; }
        public string DataTypeID { get; set; }
        public int Length { get; set; }
        public int Precision { get; set; }
        public bool Uniqueness { get; set; }
        public bool Required { get; set; }
        public string Description { get; set; }
        public string BaseColID { get; set; }
        public int BuiltInFieldTypeID { get; set; }
    }
}
