//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Model.EF._1012
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_F_AccessoriesEntry
    {
        public string ID { get; set; }
        public string AccessoriesID { get; set; }
        public int RecordNum { get; set; }
        public string Exp { get; set; }
        public string FileName { get; set; }
        public int FileSize { get; set; }
        public string SysUserID { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string OriginalPath { get; set; }
        public string FileType { get; set; }
        public string SysUserName { get; set; }
    }
}
