//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.MODEL.OA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Certificate_Other
    {
        public System.Guid DC_ID { get; set; }
        public Nullable<System.Guid> DC_DUI_ID { get; set; }
        public string DC_Name { get; set; }
        public string DC_Number { get; set; }
        public string DC_Dept { get; set; }
        public Nullable<System.DateTime> DC_Date { get; set; }
        public string DC_Expiry { get; set; }
        public string DC_Remark { get; set; }
        public Nullable<System.Guid> CREATOR { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public Nullable<System.Guid> MODIFY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<int> DC_Status { get; set; }
        public string DC_FILE { get; set; }
        public Nullable<int> DC_TYPE { get; set; }
        public string ZY1 { get; set; }
        public string LB1 { get; set; }
        public string YSZG2 { get; set; }
        public string ZXLB2 { get; set; }
        public string ZXFW2 { get; set; }
        public string YYSB3 { get; set; }
        public string YXQ3 { get; set; }
        public string ZYMC4 { get; set; }
        public string ZGJB4 { get; set; }
        public string LB4 { get; set; }
        public Nullable<System.DateTime> PZRQ4 { get; set; }
        public string DAH5 { get; set; }
        public string YZXH5 { get; set; }
        public string YZ6 { get; set; }
        public string YXQ6 { get; set; }
        public string XY7 { get; set; }
        public string YX7 { get; set; }
        public Nullable<System.DateTime> KSSJ7 { get; set; }
        public string CJ7 { get; set; }
        public string XY8 { get; set; }
        public string YX8 { get; set; }
        public Nullable<System.DateTime> KSSJ8 { get; set; }
        public string CJ8 { get; set; }
        public Nullable<int> DC_ORDER { get; set; }
    }
}
