//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.MODEL.OA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Device_Medical_Assistance
    {
        public System.Guid DDMA_ID { get; set; }
        public string DDMA_Number { get; set; }
        public Nullable<System.Guid> DDMA_Type_ID { get; set; }
        public string DDMA_Model { get; set; }
        public Nullable<System.Guid> DDMA_Location_ID { get; set; }
        public Nullable<System.Guid> DDMA_Run_State_ID { get; set; }
        public Nullable<decimal> DDMA_Price { get; set; }
        public Nullable<System.DateTime> DDMA_Buy_Date { get; set; }
        public Nullable<System.DateTime> DDMA_Guarantee_Time_Begin { get; set; }
        public Nullable<System.DateTime> DDMA_Guarantee_Time_End { get; set; }
        public Nullable<System.DateTime> DDMA_Expect_Scrap_Date { get; set; }
        public Nullable<System.DateTime> DDMA_Scrap_Date { get; set; }
        public Nullable<int> DDMA_Order { get; set; }
        public Nullable<System.Guid> CREATOR { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.Guid> MODIFY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    }
}
