//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.MODEL.OA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Handover_EVENT
    {
        public System.Guid DHE_ID { get; set; }
        public Nullable<int> DHE_TYPE { get; set; }
        public string DHE_USERTYPE { get; set; }
        public Nullable<decimal> DHE_Validity { get; set; }
        public string DHE_USERS { get; set; }
        public string DHE_PATIENT_NAME { get; set; }
        public string DHP_PATIENT_SEX { get; set; }
        public Nullable<int> DHP_PATIENT_AGE { get; set; }
        public string DHP_PATIENT_NUM { get; set; }
        public string DHP_PATIENT_BL { get; set; }
        public string DHP_PATIENT_CHECK { get; set; }
        public string DHP_PATIENT_DEPT { get; set; }
        public string DHP_PATIENT_BED { get; set; }
        public string DHP_PATIENT_TYPE { get; set; }
        public string DHP_PATIENT_MOBILE { get; set; }
        public string DHP_PATIENT_HISTORY { get; set; }
        public Nullable<System.Guid> DHP_EVENT_TYPE { get; set; }
        public Nullable<System.Guid> DHP_Reagent_TYPE { get; set; }
        public string DHP_Species { get; set; }
        public string DHP_Measure { get; set; }
        public Nullable<System.Guid> DHP_Degree { get; set; }
        public string DHP_DESC { get; set; }
        public string DHP_DEALWITH { get; set; }
        public Nullable<System.Guid> CREATOR { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.Guid> MODIFY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    }
}
