//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.MODEL.OA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_NEWS
    {
        public System.Guid BN_ID { get; set; }
        public string BN_TITLE { get; set; }
        public string BN_CONTENT { get; set; }
        public Nullable<System.Guid> BN_Type { get; set; }
        public Nullable<System.Guid> BN_SubType { get; set; }
        public Nullable<int> BN_STATE { get; set; }
        public string BN_SOURCE { get; set; }
        public Nullable<System.Guid> CREATOR { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.Guid> MODIFY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<System.Guid> BN_FILE { get; set; }
        public Nullable<bool> BN_NOTICE { get; set; }
        public Nullable<int> BN_PERMISSION { get; set; }
        public Nullable<bool> BN_TOP { get; set; }
        public Nullable<bool> BN_LEVEL { get; set; }
        public Nullable<System.Guid> BN_USERGROUP { get; set; }
        public Nullable<int> BN_DATETYPE { get; set; }
        public Nullable<int> BN_COUNT { get; set; }
        public Nullable<System.DateTime> BN_TOPDATE { get; set; }
        public string BN_PDF { get; set; }
    }
}
