//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.MODEL.OA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Radiation_EmergencyOrAccident
    {
        public System.Guid DRE_ID { get; set; }
        public Nullable<System.DateTime> DRE_Date { get; set; }
        public string DRE_Record { get; set; }
        public string DRE_HealthSituation { get; set; }
        public string DRE_Organ { get; set; }
        public Nullable<System.Guid> CREATOR { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.Guid> MODIFY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<int> DRE_Order { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
