//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.MODEL.OA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_RESEARCH_ARTICLE_WORK
    {
        public System.Guid DRAW_ID { get; set; }
        public string DRAW_NAME { get; set; }
        public string DRAW_FIRST { get; set; }
        public string DRAW_PUBLISH { get; set; }
        public Nullable<System.DateTime> DRAW_PUBLISH_DATE { get; set; }
        public Nullable<System.Guid> DRAW_PUBLISH_ADDRESS_ID { get; set; }
        public Nullable<System.Guid> DRAW_TYPE_ID { get; set; }
        public Nullable<decimal> DRAW_WORD_COUNT { get; set; }
        public Nullable<System.Guid> DRAW_PUBLISH_LEVEL_ID { get; set; }
        public string DRAW_FILE { get; set; }
        public Nullable<int> DRAW_STATE { get; set; }
        public Nullable<System.Guid> CREATOR { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.Guid> MODIFY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public string DRAW_ISBN { get; set; }
        public string DRAW_AUTHOR { get; set; }
    }
}
