//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.MODEL.OA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_RESEARCH_CHECK
    {
        public System.Guid DRC_ID { get; set; }
        public Nullable<System.DateTime> DRC_DATE { get; set; }
        public string DRC_ADDRESS { get; set; }
        public string DRC_CONTENT { get; set; }
        public string DRC_LEVEL { get; set; }
        public string DRC_INVIGILATOR { get; set; }
        public string DRC_SCORE { get; set; }
        public Nullable<System.Guid> CREATOR { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.Guid> MODIFY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public string DRC_JOBNUM { get; set; }
        public Nullable<System.Guid> DRC_DUI_ID { get; set; }
        public string DRC_DUI_NAME { get; set; }
    }
}
