//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.MODEL.OA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_RESEARCH_TEACH
    {
        public System.Guid DRT_ID { get; set; }
        public Nullable<System.DateTime> DRT_DATE { get; set; }
        public string DRT_ADDRESS { get; set; }
        public string DRT_PROJECT { get; set; }
        public string DRT_KIND { get; set; }
        public Nullable<int> DRT_COUNT { get; set; }
        public string DRT_PPT { get; set; }
        public Nullable<System.Guid> CREATOR { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.Guid> MODIFY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    }
}
