//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.MODEL.OA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Record_Rewards
    {
        public System.Guid DRR_ID { get; set; }
        public Nullable<System.Guid> DRR_Type_Id { get; set; }
        public string DRR_Name { get; set; }
        public Nullable<System.Guid> DRR_Level_Id { get; set; }
        public Nullable<System.DateTime> DRR_Date { get; set; }
        public string DRR_Dept { get; set; }
        public Nullable<int> DRR_Count { get; set; }
        public Nullable<int> DRR_Rank { get; set; }
        public string DRR_Remark { get; set; }
        public Nullable<System.Guid> CREATOR { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.Guid> MODIFY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<int> DRR_Order { get; set; }
    }
}
