//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.MODEL.OA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_RESEARCH_ARTICLE
    {
        public System.Guid DRA_ID { get; set; }
        public Nullable<System.DateTime> DRA_DATE { get; set; }
        public string DRA_TITLE { get; set; }
        public string DRA_MAGAZINE { get; set; }
        public string DRA_PAGE { get; set; }
        public Nullable<System.Guid> DRA_LEVEL { get; set; }
        public string DRA_IMPACT { get; set; }
        public string DRA_AUTHOR { get; set; }
        public string DRA_ORDER { get; set; }
        public string DRA_FILE { get; set; }
        public Nullable<int> DRA_STATE { get; set; }
        public Nullable<System.Guid> CREATOR { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.Guid> MODIFY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public string DRA_AUTHOR_NAME { get; set; }
    }
}
