//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.MODEL.OA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_WORK_EXP_BASE
    {
        public System.Guid DWE_ID { get; set; }
        public Nullable<System.Guid> DWE_DUI_ID { get; set; }
        public Nullable<System.DateTime> DWE_BEGIN { get; set; }
        public Nullable<System.DateTime> DWE_END { get; set; }
        public Nullable<bool> DWE_END_NOW { get; set; }
        public string DWE_COMPANY { get; set; }
        public Nullable<System.Guid> DWE_COMPANY_LEVEL_ID { get; set; }
        public string DWE_Province_Id { get; set; }
        public string DWE_City_Id { get; set; }
        public Nullable<System.Guid> CREATOR { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.Guid> MODIFY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<int> DWE_Status { get; set; }
        public string DWE_DATE_SUM { get; set; }
        public Nullable<int> DWE_ORDER { get; set; }
    }
}
