//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.MODEL.OA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_USERS
    {
        public System.Guid SU_ID { get; set; }
        public Nullable<System.Guid> SU_OE_ID { get; set; }
        public string SU_NAME { get; set; }
        public string SU_CODE { get; set; }
        public string SU_LOGIN { get; set; }
        public string SU_PASSWORD { get; set; }
        public Nullable<int> SU_SEX { get; set; }
        public string SU_MOBILE { get; set; }
        public string SU_OFFICEPHONE { get; set; }
        public string SU_EMAIL { get; set; }
        public string SU_FAX { get; set; }
        public string SU_ADDRESS { get; set; }
        public Nullable<bool> SU_ACTIVITY { get; set; }
        public Nullable<double> SU_ORDER { get; set; }
        public Nullable<System.Guid> SU_SD_ID { get; set; }
        public Nullable<System.DateTime> SU_INCOMPANY_TIME { get; set; }
        public string SU_WORKTIME { get; set; }
        public Nullable<System.Guid> SU_SP_ID { get; set; }
        public Nullable<System.Guid> SU_SPP_ID { get; set; }
        public Nullable<System.Guid> CREATOR { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.Guid> MODIFY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    }
}
