//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTMODEL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Bonus
    {
        public System.Guid DB_ID { get; set; }
        public Nullable<System.Guid> DB_DUI_ID { get; set; }
        public string DB_JOBNUM { get; set; }
        public string DB_USERNAME { get; set; }
        public Nullable<int> DB_YEAR { get; set; }
        public Nullable<int> DB_MONTH { get; set; }
        public Nullable<decimal> DB_XS { get; set; }
        public Nullable<decimal> DB_JJ { get; set; }
        public Nullable<decimal> DB_YY { get; set; }
        public Nullable<decimal> DB_TJ { get; set; }
        public Nullable<decimal> DB_YB { get; set; }
        public Nullable<decimal> DB_JB { get; set; }
        public Nullable<decimal> DB_CB { get; set; }
        public Nullable<decimal> DB_JIEB { get; set; }
        public Nullable<decimal> DB_JIB { get; set; }
        public Nullable<decimal> DB_BU { get; set; }
        public Nullable<decimal> DB_ZJ { get; set; }
        public Nullable<System.Guid> CREATOR { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.Guid> MODIFY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    }
}
