//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTMODEL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Device_Large_Image
    {
        public System.Guid DDLI_ID { get; set; }
        public string DDLI_Number { get; set; }
        public Nullable<System.Guid> DDLI_Type_ID { get; set; }
        public string DDLI_Model { get; set; }
        public string DDLI_License_Key { get; set; }
        public Nullable<System.Guid> DDLI_Room_Number_ID { get; set; }
        public Nullable<System.Guid> DDLI_Run_State_ID { get; set; }
        public Nullable<decimal> DDLI_Prce { get; set; }
        public Nullable<System.DateTime> DDLI_Buy_Date { get; set; }
        public Nullable<System.DateTime> DDLI_First_Time_Open_Date { get; set; }
        public Nullable<System.DateTime> DDLI_Guarantee_Time_Begin { get; set; }
        public Nullable<System.DateTime> DDLI_Guarantee_Time_End { get; set; }
        public Nullable<System.DateTime> DDLI_Expect_Scrap_Date { get; set; }
        public Nullable<System.DateTime> DDLI_Scrap_Date { get; set; }
        public Nullable<int> DDLI_Order { get; set; }
        public Nullable<System.Guid> CREATOR { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.Guid> MODIFY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    }
}
