//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTMODEL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_EDUCATION_EXP : Enterprise.Core.Interface.Data.IEntityRoot
    {
        public System.Guid DEE_ID { get; set; }
        public Nullable<System.Guid> DEE_DUI_ID { get; set; }
        public Nullable<System.Guid> DEE_Degree_Id { get; set; }
        public string DEE_Professional { get; set; }
        public string DEE_School { get; set; }
        public Nullable<System.Guid> DEE_School_SubjectionId { get; set; }
        public Nullable<System.DateTime> DEE_School_Begin { get; set; }
        public Nullable<System.DateTime> DEE_School_End { get; set; }
        public Nullable<int> DEE_School_Years { get; set; }
        public string DEE_Tutor { get; set; }
        public string DEE_Certificate_Graduation { get; set; }
        public string DEE_Certificate_Degree { get; set; }
        public Nullable<System.Guid> CREATOR { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.Guid> MODIFY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<int> DEE_Status { get; set; }
        public string DEE_School_Address { get; set; }
        public Nullable<int> DEE_ORDER { get; set; }
    }
}
