//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTMODEL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Handover_Equipment
    {
        public System.Guid DHE_ID { get; set; }
        public Nullable<int> DHE_TYPE { get; set; }
        public string DHE_USERTYPE { get; set; }
        public Nullable<decimal> DHE_Validity { get; set; }
        public string DHE_ROOM { get; set; }
        public string DHE_Equipment_TYPE { get; set; }
        public Nullable<System.Guid> DHE_Equipment_ID { get; set; }
        public string DHE_Equipment_CODE { get; set; }
        public string DHE_Equipment_NAME { get; set; }
        public string DHE_Urgency { get; set; }
        public string DHE_FAULT { get; set; }
        public string DHE_Feedback { get; set; }
        public Nullable<System.Guid> CREATOR { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.Guid> MODIFY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    }
}
