//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTMODEL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Operation_State
    {
        public System.Guid DOS_ID { get; set; }
        public Nullable<decimal> CYRS { get; set; }
        public Nullable<decimal> SSZTS { get; set; }
        public Nullable<decimal> SLYSSS { get; set; }
        public Nullable<decimal> ZYWL { get; set; }
        public Nullable<decimal> MCRFY { get; set; }
        public Nullable<decimal> YPBL { get; set; }
        public Nullable<decimal> PJZYR { get; set; }
        public Nullable<decimal> JCFY { get; set; }
        public Nullable<decimal> MZL { get; set; }
        public Nullable<decimal> MCRFYPFY { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.Guid> CREATOR { get; set; }
        public Nullable<int> YEAR { get; set; }
        public Nullable<int> MONTH { get; set; }
    }
}
