//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTMODEL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Radiation_PersonalDose : Enterprise.Core.Interface.Data.IEntityRoot
    {
        public System.Guid DRP_ID { get; set; }
        public string DRP_WorkCode { get; set; }
        public string DRP_Name { get; set; }
        public Nullable<System.DateTime> DRP_Date { get; set; }
        public Nullable<decimal> DRP_Result { get; set; }
        public string DRP_Organ { get; set; }
        public Nullable<System.Guid> CREATOR { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.Guid> MODIFY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<int> DRP_Order { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
