//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTMODEL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_RESEARCH_ISSUE : Enterprise.Core.Interface.Data.IEntityRoot
    {
        public System.Guid DRI_ID { get; set; }
        public Nullable<System.DateTime> DRI_BEGIN { get; set; }
        public Nullable<System.DateTime> DRI_END { get; set; }
        public string DRI_SOURCE { get; set; }
        public string DRI_TYPE { get; set; }
        public string DRI_NAME { get; set; }
        public Nullable<decimal> DRI_AMT { get; set; }
        public Nullable<int> DRI_COUNT { get; set; }
        public string DRI_ORDER { get; set; }
        public string DRI_FILES { get; set; }
        public Nullable<System.Guid> CREATOR { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.Guid> MODIFY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<System.Guid> DRI_TYPE_ID { get; set; }
        public string DRI_NUMBER { get; set; }
        public string DRI_OWNER { get; set; }
    }
}
