//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTMODEL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_RESEARCH_WINNERS
    {
        public System.Guid DRW_ID { get; set; }
        public Nullable<System.DateTime> DRW_DATE { get; set; }
        public string DRW_NAME { get; set; }
        public string DRW_LEVEL { get; set; }
        public Nullable<int> DRW_TOTALCOUNT { get; set; }
        public string DRW_ORDER { get; set; }
        public string DRW_FILE { get; set; }
        public Nullable<System.Guid> CREATOR { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.Guid> MODIFY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public string DRW_PROJECTNAME { get; set; }
        public string DRW_NUMBER { get; set; }
        public Nullable<System.Guid> DRW_LEVEL_ID { get; set; }
    }
}
