//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTMODEL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_RESEARCH_ARTICLE_MEETING
    {
        public System.Guid DRAM_ID { get; set; }
        public Nullable<System.DateTime> DRAM_DATE { get; set; }
        public string DRAM_TITLE { get; set; }
        public string DRAM_LEVEL { get; set; }
        public string DRAM_ORDER { get; set; }
        public string DRAM_FILE { get; set; }
        public Nullable<int> DRAM_STATE { get; set; }
        public Nullable<System.Guid> CREATOR { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.Guid> MODIFY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public string DRAM_ARTICLE { get; set; }
        public string DRAM_ADDRESS { get; set; }
        public string DRAM_AUTHOR_NAME { get; set; }
        public Nullable<System.Guid> DRAM_Form_ID { get; set; }
        public string DRAM_AUTHOR { get; set; }
    }
}
