//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTMODEL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_SCHEDULE_GROUP : Enterprise.Core.Interface.Data.IEntityRoot
    {
        public System.Guid DSG_ID { get; set; }
        public string DSG_NAME { get; set; }
        public string DSG_REMARK { get; set; }
        public Nullable<int> DSG_ORDER { get; set; }
        public Nullable<System.Guid> DSG_MANAGER { get; set; }
        public Nullable<System.Guid> CREATOR { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.Guid> MODIFY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    }
}
