//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTMODEL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_SCHEDULING_DETAIL
    {
        public System.Guid DSD_ID { get; set; }
        public Nullable<System.Guid> DSD_DS_ID { get; set; }
        public Nullable<System.DateTime> DSD_DATE { get; set; }
        public Nullable<System.Guid> DSD_USERID { get; set; }
        public string DSD_USERNAME { get; set; }
        public Nullable<System.Guid> DSD_POSTIONID { get; set; }
        public string DSD_POSTIONNAME { get; set; }
        public Nullable<int> DSD_TYPE { get; set; }
        public Nullable<System.Guid> DSD_DSG_ID { get; set; }
        public Nullable<System.Guid> CREATOR { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.Guid> MODIFY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    }
}
