//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTMODEL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_USER_INFO : Enterprise.Core.Interface.Data.IEntityRoot
    {
        public System.Guid DUI_ID { get; set; }
        public Nullable<System.Guid> DUI_SU_ID { get; set; }
        public string DUI_WORKSTATUS { get; set; }
        public string DUI_PWD { get; set; }
        public string DUI_NAME { get; set; }
        public string DUI_SEX { get; set; }
        public Nullable<System.DateTime> DUI_BIRTHDAY { get; set; }
        public string DUI_IDCARD_NUMBER { get; set; }
        public string DUI_IDCARD1 { get; set; }
        public string DUI_IDCARD2 { get; set; }
        public Nullable<int> DUI_AGE { get; set; }
        public string DUI_PY1 { get; set; }
        public string DUI_PY2 { get; set; }
        public Nullable<System.Guid> DUI_Nation_Id { get; set; }
        public string DUI_NativePlace_Province_Id { get; set; }
        public string DUI_NativePlace_City_Id { get; set; }
        public string DUI_NativePlace_County_Id { get; set; }
        public string DUI_BirthPlace_Province_Id { get; set; }
        public string DUI_BirthPlace_City_Id { get; set; }
        public string DUI_BirthPlace_County_Id { get; set; }
        public Nullable<System.Guid> DUI_PoliticalFaction_Id { get; set; }
        public Nullable<System.DateTime> DUI_PoliticalFaction_JoinDate { get; set; }
        public Nullable<System.DateTime> DUI_JoinInWork_Date { get; set; }
        public Nullable<int> DUI_JoinInWork_Years { get; set; }
        public Nullable<System.DateTime> DUI_JoinInRadiat_Date { get; set; }
        public Nullable<int> DUI_JoinInRadiat_Years { get; set; }
        public Nullable<System.DateTime> DUI_JoinInHospital_Date { get; set; }
        public Nullable<int> DUI_JoinInHospital_Years { get; set; }
        public Nullable<System.DateTime> DUI_EmploymentContract_Begin { get; set; }
        public Nullable<System.DateTime> DUI_EmploymentContract_End { get; set; }
        public Nullable<System.Guid> DUI_EmploymentContract_Folder { get; set; }
        public string DUI_JobNumber { get; set; }
        public Nullable<System.Guid> DUI_HospitalBranch_In { get; set; }
        public Nullable<System.Guid> DUI_Staff_Type { get; set; }
        public Nullable<System.Guid> DUI_Position_Id { get; set; }
        public string DUI_Job { get; set; }
        public Nullable<System.Guid> DUI_Educational_Id { get; set; }
        public Nullable<System.Guid> DUI_Degree_Id { get; set; }
        public string DUI_Professionals { get; set; }
        public string DUI_Telephone_Long { get; set; }
        public Nullable<System.Guid> DUI_Telephone_Short_Operate_Id { get; set; }
        public string DUI_Telephone_Short_Number { get; set; }
        public string DUI_Telephone_Bakeup { get; set; }
        public string DUI_Email1 { get; set; }
        public string DUI_Email2 { get; set; }
        public string DUI_Car_Number { get; set; }
        public Nullable<System.Guid> DUI_MaritalStatus_Id { get; set; }
        public Nullable<System.Guid> CREATOR { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.Guid> MODIFY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<int> DUI_Status { get; set; }
        public string DUI_MYPIC { get; set; }
    }
}
