//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTMODEL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_User_Holiday
    {
        public System.Guid DUH_ID { get; set; }
        public Nullable<System.Guid> DUI_ID { get; set; }
        public string DUI_JONNUM { get; set; }
        public string DUI_NAME { get; set; }
        public Nullable<int> DUI_YEAR { get; set; }
        public Nullable<int> DUI_TYPE2COUNT { get; set; }
        public Nullable<int> DUI_TYPE3COUNT { get; set; }
        public Nullable<System.Guid> CREATOR { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.Guid> MODIFY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    }
}
