//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTMODEL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSP_Matrix_PressreFactor
    {
        public int Factor_ID { get; set; }
        public int Material_ID { get; set; }
        public decimal Operating_Temperature { get; set; }
        public decimal Factor_Value { get; set; }
    }
}
