//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTMODEL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSP_Matrix_TorqueTubeRate
    {
        public int Rate_ID { get; set; }
        public Nullable<int> Sensor_ID { get; set; }
        public Nullable<int> Material_ID { get; set; }
        public Nullable<int> Thickness_ID { get; set; }
        public Nullable<decimal> TR_Value { get; set; }
    }
}
