//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTMODEL.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalOAEntities : DbContext
    {
        public HospitalOAEntities()
            : base("name=HospitalOAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DB_Audit> DB_Audit { get; set; }
        public DbSet<DB_Bonus> DB_Bonus { get; set; }
        public DbSet<DB_Certificate_Other> DB_Certificate_Other { get; set; }
        public DbSet<DB_Device_IT> DB_Device_IT { get; set; }
        public DbSet<DB_Device_Large_Image> DB_Device_Large_Image { get; set; }
        public DbSet<DB_Device_Medical_Assistance> DB_Device_Medical_Assistance { get; set; }
        public DbSet<DB_EDUCATION_EXP> DB_EDUCATION_EXP { get; set; }
        public DbSet<DB_Handover_Equipment> DB_Handover_Equipment { get; set; }
        public DbSet<DB_Handover_EVENT> DB_Handover_EVENT { get; set; }
        public DbSet<DB_Handover_Patient> DB_Handover_Patient { get; set; }
        public DbSet<DB_Holiday> DB_Holiday { get; set; }
        public DbSet<DB_Honor> DB_Honor { get; set; }
        public DbSet<DB_NEWS> DB_NEWS { get; set; }
        public DbSet<DB_Operation_State> DB_Operation_State { get; set; }
        public DbSet<DB_ParttimeJob_AcademicJournals> DB_ParttimeJob_AcademicJournals { get; set; }
        public DbSet<DB_ParttimeJob_CommitteeService> DB_ParttimeJob_CommitteeService { get; set; }
        public DbSet<DB_ParttimeJob_GraduateStudentTutor> DB_ParttimeJob_GraduateStudentTutor { get; set; }
        public DbSet<DB_Position_State> DB_Position_State { get; set; }
        public DbSet<DB_Radiation> DB_Radiation { get; set; }
        public DbSet<DB_Radiation_BasicInfo> DB_Radiation_BasicInfo { get; set; }
        public DbSet<DB_Radiation_EmergencyOrAccident> DB_Radiation_EmergencyOrAccident { get; set; }
        public DbSet<DB_Radiation_HealthExamination> DB_Radiation_HealthExamination { get; set; }
        public DbSet<DB_Radiation_PersonalDose> DB_Radiation_PersonalDose { get; set; }
        public DbSet<DB_Radiation_TrainCheck> DB_Radiation_TrainCheck { get; set; }
        public DbSet<DB_Record_Punishments> DB_Record_Punishments { get; set; }
        public DbSet<DB_Record_Rewards> DB_Record_Rewards { get; set; }
        public DbSet<DB_RESEARCH_ARTICLE> DB_RESEARCH_ARTICLE { get; set; }
        public DbSet<DB_RESEARCH_ARTICLE_MEETING> DB_RESEARCH_ARTICLE_MEETING { get; set; }
        public DbSet<DB_RESEARCH_ARTICLE_WORK> DB_RESEARCH_ARTICLE_WORK { get; set; }
        public DbSet<DB_RESEARCH_CHECK> DB_RESEARCH_CHECK { get; set; }
        public DbSet<DB_RESEARCH_ISSUE> DB_RESEARCH_ISSUE { get; set; }
        public DbSet<DB_RESEARCH_TEACH> DB_RESEARCH_TEACH { get; set; }
        public DbSet<DB_RESEARCH_WINNERS> DB_RESEARCH_WINNERS { get; set; }
        public DbSet<DB_SCHEDULE_GROUP> DB_SCHEDULE_GROUP { get; set; }
        public DbSet<DB_SCHEDULE_GROUP_POSITION> DB_SCHEDULE_GROUP_POSITION { get; set; }
        public DbSet<DB_SCHEDULE_GROUP_TYPE> DB_SCHEDULE_GROUP_TYPE { get; set; }
        public DbSet<DB_SCHEDULING> DB_SCHEDULING { get; set; }
        public DbSet<DB_SCHEDULING_DETAIL> DB_SCHEDULING_DETAIL { get; set; }
        public DbSet<DB_TRAIN_CONTINUE> DB_TRAIN_CONTINUE { get; set; }
        public DbSet<DB_TRAIN_FOREIGN> DB_TRAIN_FOREIGN { get; set; }
        public DbSet<DB_TRAIN_INLAND> DB_TRAIN_INLAND { get; set; }
        public DbSet<DB_User_Holiday> DB_User_Holiday { get; set; }
        public DbSet<DB_USER_INFO> DB_USER_INFO { get; set; }
        public DbSet<DB_WORK_EXP_BASE> DB_WORK_EXP_BASE { get; set; }
        public DbSet<DB_WORK_EXP_SELF> DB_WORK_EXP_SELF { get; set; }
        public DbSet<SYS_DEPT> SYS_DEPT { get; set; }
        public DbSet<SYS_DISTINCT> SYS_DISTINCT { get; set; }
        public DbSet<SYS_FILES> SYS_FILES { get; set; }
        public DbSet<SYS_Location> SYS_Location { get; set; }
        public DbSet<SYS_MENU> SYS_MENU { get; set; }
        public DbSet<SYS_USER_GROUP> SYS_USER_GROUP { get; set; }
        public DbSet<SYS_USER_GROUP_MENU> SYS_USER_GROUP_MENU { get; set; }
        public DbSet<SYS_USER_GROUP_USERS> SYS_USER_GROUP_USERS { get; set; }
        public DbSet<SYS_USERS> SYS_USERS { get; set; }
        public DbSet<import> imports { get; set; }
        public DbSet<SYS_MENU2> SYS_MENU2 { get; set; }
    }
}
