//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTMODEL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_FILES
    {
        public System.Guid SF_ID { get; set; }
        public Nullable<System.Guid> SF_FORDER { get; set; }
        public string SF_NAME { get; set; }
        public string SF_FILEURL { get; set; }
        public string SF_EXT { get; set; }
        public Nullable<decimal> SF_SIZE { get; set; }
        public Nullable<System.Guid> CREATOR { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
    }
}
