//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTMODEL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_DISTINCT : Enterprise.Core.Interface.Data.IEntityRoot
    {
        public System.Guid SD_ID { get; set; }
        public Nullable<System.Guid> SD_PID { get; set; }
        public string SD_NAME { get; set; }
        public Nullable<decimal> SD_ORDER { get; set; }
        public string SD_VALUE { get; set; }
        public string SD_VALUE1 { get; set; }
        public string SD_VALUE2 { get; set; }
        public string SD_VALUE3 { get; set; }
        public string SD_VALUE4 { get; set; }
        public string SD_VALUE5 { get; set; }
        public Nullable<System.Guid> CREATOR { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.Guid> MODIFY { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    }
}
