//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTMODEL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Location
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string CountryRegionCode { get; set; }
        public string StateCode { get; set; }
        public string CityCode { get; set; }
        public string RegionCode { get; set; }
        public Nullable<int> Level { get; set; }
    }
}
