//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTMODEL.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LocalTestDBEntities : DbContext
    {
        public LocalTestDBEntities()
            : base("name=LocalTestDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DSP_Displacer_Material> DSP_Displacer_Material { get; set; }
        public DbSet<DSP_HeadFlangeSize> DSP_HeadFlangeSize { get; set; }
        public DbSet<DSP_Matrix_DisplacerAlternateWeight> DSP_Matrix_DisplacerAlternateWeight { get; set; }
        public DbSet<DSP_Matrix_DisplacerDMR> DSP_Matrix_DisplacerDMR { get; set; }
        public DbSet<DSP_Matrix_DisplacerWeight> DSP_Matrix_DisplacerWeight { get; set; }
        public DbSet<DSP_Matrix_MINPB> DSP_Matrix_MINPB { get; set; }
        public DbSet<DSP_Matrix_PressreFactor> DSP_Matrix_PressreFactor { get; set; }
        public DbSet<DSP_Matrix_TorqueTubeRate> DSP_Matrix_TorqueTubeRate { get; set; }
        public DbSet<DSP_Nace> DSP_Nace { get; set; }
        public DbSet<DSP_Pilot> DSP_Pilot { get; set; }
        public DbSet<DSP_Sensor> DSP_Sensor { get; set; }
        public DbSet<DSP_Sensor_Size_Info> DSP_Sensor_Size_Info { get; set; }
        public DbSet<DSP_Sensor_Thickness_Info> DSP_Sensor_Thickness_Info { get; set; }
        public DbSet<DSP_TT_Material> DSP_TT_Material { get; set; }
        public DbSet<DSP_TT_WallThickness> DSP_TT_WallThickness { get; set; }
    }
}
