//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.EF.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EFLocalTest : DbContext
    {
        public EFLocalTest()
            : base("name=EFLocalTest")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FLEXOrg> FLEXOrgs { get; set; }
        public DbSet<OrderTypeTranslation> OrderTypeTranslations { get; set; }
        public DbSet<T_F_Access> T_F_Access { get; set; }
        public DbSet<T_F_Accessories> T_F_Accessories { get; set; }
        public DbSet<T_F_AccessoriesContent> T_F_AccessoriesContent { get; set; }
        public DbSet<T_F_AccessoriesEntry> T_F_AccessoriesEntry { get; set; }
        public DbSet<T_F_BusinessFlow> T_F_BusinessFlow { get; set; }
        public DbSet<T_F_BusinessFlowActivity> T_F_BusinessFlowActivity { get; set; }
        public DbSet<T_F_BusinessFlowActivityOutput> T_F_BusinessFlowActivityOutput { get; set; }
        public DbSet<T_F_BusinessFlowCatalog> T_F_BusinessFlowCatalog { get; set; }
        public DbSet<T_F_BusinessFlowCondition> T_F_BusinessFlowCondition { get; set; }
        public DbSet<T_F_BusinessFlowEntity> T_F_BusinessFlowEntity { get; set; }
        public DbSet<T_F_BusinessFlowVariable> T_F_BusinessFlowVariable { get; set; }
        public DbSet<T_F_Demo> T_F_Demo { get; set; }
        public DbSet<T_F_DeskInfo> T_F_DeskInfo { get; set; }
        public DbSet<T_F_HistoryData> T_F_HistoryData { get; set; }
        public DbSet<T_F_Images> T_F_Images { get; set; }
        public DbSet<T_F_ItemTemplate> T_F_ItemTemplate { get; set; }
        public DbSet<T_F_Log> T_F_Log { get; set; }
        public DbSet<T_F_Menu> T_F_Menu { get; set; }
        public DbSet<T_F_Message> T_F_Message { get; set; }
        public DbSet<T_F_MetaData> T_F_MetaData { get; set; }
        public DbSet<T_F_MetaData_DataEntity> T_F_MetaData_DataEntity { get; set; }
        public DbSet<T_F_MetaData_DataEntityCol> T_F_MetaData_DataEntityCol { get; set; }
        public DbSet<T_F_MetaData_DataTypeNative> T_F_MetaData_DataTypeNative { get; set; }
        public DbSet<T_F_MetaData_UIInstance> T_F_MetaData_UIInstance { get; set; }
        public DbSet<T_F_Offices> T_F_Offices { get; set; }
        public DbSet<T_F_OperationLog> T_F_OperationLog { get; set; }
        public DbSet<T_F_Parameter> T_F_Parameter { get; set; }
        public DbSet<T_F_PrintConfig> T_F_PrintConfig { get; set; }
        public DbSet<T_F_ProcedureGroup> T_F_ProcedureGroup { get; set; }
        public DbSet<T_F_ProcedureInfo> T_F_ProcedureInfo { get; set; }
        public DbSet<T_F_ProcedureParamInfo> T_F_ProcedureParamInfo { get; set; }
        public DbSet<T_F_ProcedureReference> T_F_ProcedureReference { get; set; }
        public DbSet<T_F_Project> T_F_Project { get; set; }
        public DbSet<T_F_ProjectType> T_F_ProjectType { get; set; }
        public DbSet<T_F_ReportQuerySchema> T_F_ReportQuerySchema { get; set; }
        public DbSet<T_F_Solution> T_F_Solution { get; set; }
        public DbSet<T_F_TypeTemplate> T_F_TypeTemplate { get; set; }
        public DbSet<T_F_TypeTemplateGroup> T_F_TypeTemplateGroup { get; set; }
    }
}
