//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_F_ProcedureParamInfo
    {
        public string ID { get; set; }
        public string ProcedureID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public int IsOut { get; set; }
    }
}
