//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_F_MetaData
    {
        public string ID { get; set; }
        public string ProjectID { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string Type { get; set; }
        public string Remark { get; set; }
        public string MetaData { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string XmlMetaData { get; set; }
    }
}
