//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_F_BusinessFlowActivity
    {
        public string ID { get; set; }
        public string BusinessFlowID { get; set; }
        public string QualifiedID { get; set; }
        public int ActivityOrder { get; set; }
        public int IfElseOrder { get; set; }
        public int WhileOrder { get; set; }
        public int SequenceOrder { get; set; }
        public string Subject { get; set; }
        public string Operation { get; set; }
        public string Description { get; set; }
    }
}
