//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_F_MetaData_DataEntity
    {
        public string EntityID { get; set; }
        public string Name { get; set; }
        public int OrderID { get; set; }
        public string TableName { get; set; }
        public string ClassName { get; set; }
        public int EntityTypeID { get; set; }
        public string Description { get; set; }
        public bool IsAbstract { get; set; }
        public string BaseEntityID { get; set; }
        public string ParentID { get; set; }
        public int LevelNum { get; set; }
        public bool IsDetail { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string SchemaXML { get; set; }
    }
}
