//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_F_Menu
    {
        public T_F_Menu()
        {
            this.T_F_Menu1 = new HashSet<T_F_Menu>();
        }
    
        public string ID { get; set; }
        public string Num { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public Nullable<int> OpenMode { get; set; }
        public string Privilege { get; set; }
        public string RequestObject { get; set; }
        public string ImagePath { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<bool> Visible { get; set; }
        public string Platform { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsFixed { get; set; }
        public Nullable<bool> IsAutoOpen { get; set; }
        public string ParentID { get; set; }
    
        public virtual ICollection<T_F_Menu> T_F_Menu1 { get; set; }
        public virtual T_F_Menu T_F_Menu2 { get; set; }
    }
}
