//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_F_Access
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string Num { get; set; }
        public int Mask { get; set; }
        public int OrderID { get; set; }
        public string Description { get; set; }
        public string ParentID { get; set; }
        public int LevelNum { get; set; }
        public bool IsDetail { get; set; }
        public bool IsGroup { get; set; }
        public string Message { get; set; }
        public bool Forbidden { get; set; }
    }
}
