//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_F_Log
    {
        public string ID { get; set; }
        public string UserID { get; set; }
        public string IP { get; set; }
        public string HostName { get; set; }
        public string OperationName { get; set; }
        public Nullable<int> OperationType { get; set; }
        public string OperationContent { get; set; }
        public Nullable<System.DateTime> OperationTime { get; set; }
    }
}
