//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_F_ReportQuerySchema
    {
        public string ID { get; set; }
        public string SchemaName { get; set; }
        public string ReportID { get; set; }
        public string Query { get; set; }
        public string UserID { get; set; }
    }
}
