//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_F_BusinessFlowActivityOutput
    {
        public string ID { get; set; }
        public string BusinessFlowID { get; set; }
        public string QualifiedID { get; set; }
        public string VariableID { get; set; }
        public string EntityProperty { get; set; }
        public string EntityID { get; set; }
    }
}
